name: all_flutter_work
description: A new Flutter project.

publish_to: ''


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  url_launcher: ^6.1.10
  image_picker: ^0.8.6+4
  path_provider: ^2.0.13
  table_calendar: ^3.0.8
  curved_navigation_bar: ^1.0.3
 # percent_indicator: ^2.1.7+2




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
